some_text = input("Введите какой то текст: ")
sym_some_text = len(some_text)
sym_some_text2 = words = len(some_text.split())
print("Количество введенный символов: ", sym_some_text2)
print("Общее число слов:", words)
